package hu.boltseged.pickup;

import com.fasterxml.jackson.databind.ObjectMapper; import hu.boltseged.account.Account; import hu.boltseged.shipment.*; import hu.boltseged.shipping.ShippingProvider; import org.junit.jupiter.api.Test; import org.springframework.web.server.ResponseStatusException; import java.math.BigDecimal; import java.time.*; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;

class PickupServiceTest {
 private final PickupBookingRepository bookings=mock(PickupBookingRepository.class); private final ShipmentRepository shipments=mock(ShipmentRepository.class); private final ShippingProvider dhl=mock(ShippingProvider.class); private final ObjectMapper json=new ObjectMapper(); private final PickupService service=new PickupService(bookings,shipments,dhl,json);
 private Account account(String email){Account a=new Account("Sender",email,"hash","CUSTOMER");a.updateCompanyProfile("Sender",null,null,"Sender contact","HU","1051","Budapest","Sender Street",null,null,"+361","Saved Pickup","Pickup contact","HU","8200","Veszprem","Pickup Street 1",null,null,"+36201234567","pickup@example.com");return a;}
 private PickupController.AddressRequest address(){return new PickupController.AddressRequest("Company","Contact","HU","8200","Veszprem","Street 1",null,null,"+36201234567","a@b.com");}
 private Shipment shipment(Account account,String key,int packages){List<Shipment.PackageInput> inputs=new ArrayList<>();for(int i=0;i<packages;i++)inputs.add(new Shipment.PackageInput(new BigDecimal("1.5"),BigDecimal.TEN,BigDecimal.TEN,BigDecimal.TEN));Shipment s=new Shipment(account,key,"P",LocalDate.now(),"{\"companyName\":\"Company\",\"contactName\":\"Contact\",\"countryCode\":\"HU\",\"postalCode\":\"8200\",\"cityName\":\"Veszprem\",\"addressLine1\":\"Street 1\",\"phone\":\"+36201234567\",\"email\":\"a@b.com\"}","{\"countryCode\":\"DE\"}",inputs);s.setCustoms("{\"customsDeclarable\":false}");s.complete("TRACK-"+key,"DHL-"+key,Collections.nCopies(packages,"PIECE"),BigDecimal.ONE,"HUF");return s;}
 @Test void calculatesTotalsServerSideAndPersistsSuccessfulBooking(){Account account=account("a@b.com");Shipment a=shipment(account,"a",2),b=shipment(account,"b",1);when(shipments.findAllForPickupByIdIn(any())).thenReturn(List.of(a,b));when(dhl.createPickup(any())).thenReturn(new ShippingProvider.PickupResult(List.of("CONFIRM"),"12:00","2026-09-21",List.of()));when(bookings.save(any())).thenAnswer(i->i.getArgument(0));PickupController.CreateRequest request=new PickupController.CreateRequest(List.of(a.getId(),b.getId()),LocalDate.now().plusDays(1),LocalTime.of(13,0),LocalTime.of(17,0),address(),"business","reception",null);PickupBooking result=service.create(account,request);assertEquals(3,result.getPackageCount());assertEquals(0,new BigDecimal("4.5").compareTo(result.getTotalWeight()));verify(dhl).createPickup(argThat(x->x.shipments().size()==2));verify(bookings).save(result);}
 @Test void rejectsForeignShipmentAsNotFound(){Account owner=account("owner@b.com"),attacker=account("attacker@b.com");Shipment foreign=shipment(owner,"x",1);when(shipments.findAllForPickupByIdIn(any())).thenReturn(List.of(foreign));PickupController.CreateRequest request=new PickupController.CreateRequest(List.of(foreign.getId()),LocalDate.now().plusDays(1),LocalTime.NOON,LocalTime.of(17,0),address(),"business",null,null);assertThrows(ResponseStatusException.class,()->service.create(attacker,request));verifyNoInteractions(dhl);}
 @Test void rejectsShipmentAlreadyInBookedPickupBeforeCallingDhl(){Account account=account("a@b.com");Shipment booked=shipment(account,"booked",1);when(shipments.findAllForPickupByIdIn(any())).thenReturn(List.of(booked));when(bookings.existsByStatusAndShipments_Id("BOOKED",booked.getId())).thenReturn(true);PickupController.CreateRequest request=new PickupController.CreateRequest(List.of(booked.getId()),LocalDate.now().plusDays(1),LocalTime.NOON,LocalTime.of(17,0),address(),"business",null,null);ResponseStatusException error=assertThrows(ResponseStatusException.class,()->service.create(account,request));assertEquals(org.springframework.http.HttpStatus.CONFLICT,error.getStatusCode());assertTrue(error.getReason().contains(booked.getMasterTrackingNumber()));verifyNoInteractions(dhl);}
 @Test void mapsPersistedCustomsValueAndCurrencyToPickupShipment(){Account account=account("a@b.com");Shipment customs=shipment(account,"customs",1);customs.setCustoms("{\"customsDeclarable\":true,\"declaredValue\":50,\"declaredValueCurrency\":\"USD\"}");when(shipments.findAllForPickupByIdIn(any())).thenReturn(List.of(customs));when(dhl.createPickup(any())).thenReturn(new ShippingProvider.PickupResult(List.of("CONFIRM"),"12:00","2026-09-21",List.of()));when(bookings.save(any())).thenAnswer(i->i.getArgument(0));PickupController.CreateRequest request=new PickupController.CreateRequest(List.of(customs.getId()),LocalDate.now().plusDays(1),LocalTime.NOON,LocalTime.of(17,0),address(),"business",null,null);service.create(account,request);org.mockito.ArgumentCaptor<ShippingProvider.PickupRequest> captured=org.mockito.ArgumentCaptor.forClass(ShippingProvider.PickupRequest.class);verify(dhl).createPickup(captured.capture());ShippingProvider.PickupShipment detail=captured.getValue().shipments().getFirst();assertTrue(detail.customsDeclarable());assertEquals(new BigDecimal("50"),detail.declaredValue());assertEquals("USD",detail.declaredValueCurrency());}
 @Test void rejectsOldCustomsShipmentWithoutPersistedValueBeforeCallingDhl(){Account account=account("a@b.com");Shipment customs=shipment(account,"legacy",1);customs.setCustoms("{\"customsDeclarable\":true}");when(shipments.findAllForPickupByIdIn(any())).thenReturn(List.of(customs));PickupController.CreateRequest request=new PickupController.CreateRequest(List.of(customs.getId()),LocalDate.now().plusDays(1),LocalTime.NOON,LocalTime.of(17,0),address(),"business",null,null);ResponseStatusException error=assertThrows(ResponseStatusException.class,()->service.create(account,request));assertEquals(org.springframework.http.HttpStatus.BAD_REQUEST,error.getStatusCode());assertTrue(error.getReason().contains("nem áll rendelkezésre"));verifyNoInteractions(dhl);}
 @Test void usesSavedPickupAddressInsteadOfSubmittedAddress(){Account account=account("a@b.com");Shipment shipment=shipment(account,"saved",1);when(shipments.findAllForPickupByIdIn(any())).thenReturn(List.of(shipment));when(dhl.createPickup(any())).thenReturn(new ShippingProvider.PickupResult(List.of("CONFIRM"),"12:00","2026-09-21",List.of()));when(bookings.save(any())).thenAnswer(i->i.getArgument(0));service.create(account,new PickupController.CreateRequest(List.of(shipment.getId()),LocalDate.now().plusDays(1),LocalTime.NOON,LocalTime.of(17,0),address(),"business",null,null));org.mockito.ArgumentCaptor<ShippingProvider.PickupRequest> captured=org.mockito.ArgumentCaptor.forClass(ShippingProvider.PickupRequest.class);verify(dhl).createPickup(captured.capture());assertEquals("Saved Pickup",captured.getValue().pickupAddress().companyName());assertEquals("Pickup Street 1",captured.getValue().pickupAddress().addressLine1());}
 @Test void incompleteSavedPickupAddressIsRejected(){Account account=new Account("Sender","a@b.com","hash","CUSTOMER");ResponseStatusException error=assertThrows(ResponseStatusException.class,()->service.create(account,new PickupController.CreateRequest(List.of(UUID.randomUUID()),LocalDate.now().plusDays(1),LocalTime.NOON,LocalTime.of(17,0),address(),"business",null,null)));assertTrue(error.getReason().contains("Feladói adatok"));verifyNoInteractions(shipments,dhl);}
 @Test void pickupTimesMustUseQuarterHourMinutes(){PickupController.CreateRequest invalid=new PickupController.CreateRequest(List.of(UUID.randomUUID()),LocalDate.now().plusDays(1),LocalTime.of(13,10),LocalTime.of(17,0),null,"business",null,null);assertFalse(invalid.hasQuarterHourTimes());assertTrue(new PickupController.CreateRequest(List.of(UUID.randomUUID()),LocalDate.now().plusDays(1),LocalTime.of(13,15),LocalTime.of(17,45),null,"business",null,null).hasQuarterHourTimes());}
 @Test void cancellationCannotTargetAnotherCustomersBooking(){Account account=account("a@b.com");UUID id=UUID.randomUUID();when(bookings.findByIdAndAccountId(id,account.getId())).thenReturn(Optional.empty());assertThrows(ResponseStatusException.class,()->service.cancel(account,id));verifyNoInteractions(dhl);}
 @Test void successfulCancellationCallsDhlBeforePersistingCancelledStatus(){Account account=account("a@b.com");account.updateCompanyProfile(null,null,null,"Requestor");PickupBooking booking=new PickupBooking(account,"[\"CONFIRM\"]","[]",LocalDate.now().plusDays(1),LocalTime.NOON,LocalTime.of(17,0),"{}",1,BigDecimal.ONE,List.of());when(bookings.findByIdAndAccountId(booking.getId(),account.getId())).thenReturn(Optional.of(booking));when(bookings.save(booking)).thenReturn(booking);PickupBooking result=service.cancel(account,booking.getId());verify(dhl).cancelPickup("CONFIRM","Requestor","Customer cancelled pickup");verify(bookings).save(booking);assertEquals("CANCELLED",result.getStatus());}
}
