package hu.boltseged.shipment;

import hu.boltseged.account.Account; import jakarta.persistence.*; import org.hibernate.annotations.JdbcTypeCode; import org.hibernate.type.SqlTypes; import java.math.BigDecimal; import java.time.*; import java.util.*;
@Entity @Table(name="shipments", uniqueConstraints=@UniqueConstraint(columnNames={"account_id","idempotency_key"}))
public class Shipment {
  @Id private UUID id; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="account_id",nullable=false) private Account account;
  private String idempotencyKey, masterTrackingNumber, dhlShipmentId, dhlProductCode; private LocalDate shipDate; @JdbcTypeCode(SqlTypes.JSON) @Column(columnDefinition="jsonb") private String sender; @JdbcTypeCode(SqlTypes.JSON) @Column(columnDefinition="jsonb") private String recipient; @JdbcTypeCode(SqlTypes.JSON) @Column(columnDefinition="jsonb") private String customs; private BigDecimal dhlEstimatedCost, customerPrice; @Column(length=3) private String currency; private String status,billingStatus; private Instant invoicedAt,createdAt,updatedAt;
  @OneToMany(mappedBy="shipment",cascade=CascadeType.ALL,orphanRemoval=true,fetch=FetchType.EAGER) private List<ShipmentPackage> packages=new ArrayList<>();
  protected Shipment() {}
  public Shipment(Account a,String key,String product,LocalDate date,String sender,String recipient,List<PackageInput> ps){id=UUID.randomUUID();account=a;idempotencyKey=key;dhlProductCode=product;shipDate=date;this.sender=sender;this.recipient=recipient;currency="EUR";status="PENDING";billingStatus="UNBILLED";createdAt=Instant.now();updatedAt=createdAt;for(int i=0;i<ps.size();i++)packages.add(new ShipmentPackage(this,i+1,ps.get(i)));}
  public UUID getId(){return id;} public Account getAccount(){return account;} public String getMasterTrackingNumber(){return masterTrackingNumber;} public String getDhlProductCode(){return dhlProductCode;} public String getStatus(){return status;} public List<ShipmentPackage> getPackages(){return packages;} public BigDecimal getDhlEstimatedCost(){return dhlEstimatedCost;} public BigDecimal getCustomerPrice(){return customerPrice;} public String getBillingStatus(){return billingStatus;} public void price(BigDecimal cost,BigDecimal customer){dhlEstimatedCost=cost;customerPrice=customer;} public void complete(String master,String dhlId,List<String> pieces,BigDecimal cost,String currency){masterTrackingNumber=master;dhlShipmentId=dhlId;this.currency=currency;for(int i=0;i<packages.size();i++)packages.get(i).setTrackingNumber(i<pieces.size()?pieces.get(i):null);status="CREATED";updatedAt=Instant.now();} public void fail(){status="FAILED";updatedAt=Instant.now();} public void invoice(){billingStatus="INVOICED";invoicedAt=Instant.now();}
  public LocalDate getShipDate(){return shipDate;} public Instant getCreatedAt(){return createdAt;} public String getSender(){return sender;} public String getRecipient(){return recipient;} public String getCustoms(){return customs;} public void setCustoms(String value){customs=value;} public String getCurrency(){return currency;} public record PackageInput(BigDecimal weight,BigDecimal length,BigDecimal width,BigDecimal height){}
}

