package hu.boltseged.shipment;

import com.fasterxml.jackson.databind.*; import hu.boltseged.account.Account; import hu.boltseged.label.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import java.io.*; import java.math.*; import java.time.*; import java.util.*;

@RestController @RequestMapping("/api/shipments") public class ShipmentController {
 private final ShipmentRepository repo; private final ShipmentService service; private final ShipmentLabelRepository labels; private final LabelStorage storage; private final ObjectMapper json;
 ShipmentController(ShipmentRepository r,ShipmentService s,ShipmentLabelRepository l,LabelStorage st,ObjectMapper j){repo=r;service=s;labels=l;storage=st;json=j;}
 @GetMapping List<CustomerShipmentView> list(){return repo.findByAccountIdOrderByCreatedAtDesc(current().getId()).stream().map(this::customerView).toList();}
 @GetMapping("/pickup-eligible") List<CustomerShipmentView> pickupEligible(){return repo.findPickupEligibleByAccountId(current().getId()).stream().map(this::customerView).toList();}
 @PostMapping("/quotes") List<CustomerQuote> quote(@Valid @RequestBody QuoteRequest x){return service.quote(current(),x);}
 @PostMapping ResponseEntity<CustomerShipmentView> create(@RequestHeader("Idempotency-Key")@NotBlank String key,@Valid @RequestBody CreateRequest x){Shipment s=service.create(current(),key,x);HttpStatus status=switch(s.getStatus()){case "PENDING"->HttpStatus.ACCEPTED;case "FAILED"->HttpStatus.CONFLICT;default->HttpStatus.CREATED;};return ResponseEntity.status(status).body(customerView(s));}
 @GetMapping("/{id}") CustomerShipmentView get(@PathVariable UUID id){return customerView(repo.findDetailedById(id).filter(s->s.getAccount().getId().equals(current().getId())).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND)));}
 @GetMapping("/{shipmentId}/labels/{labelId}") ResponseEntity<byte[]> download(@PathVariable UUID shipmentId,@PathVariable UUID labelId)throws IOException{ShipmentLabel l=labels.findByIdAndShipmentId(labelId,shipmentId).filter(x->x.getShipment().getAccount().getId().equals(current().getId())||"ADMIN".equals(current().getRole())).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));try(InputStream in=storage.get(l.getStorageKey())){return ResponseEntity.ok().contentType(MediaType.parseMediaType(l.getContentType())).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+l.getFileName()+"\"").body(in.readAllBytes());}}
 private CustomerShipmentView customerView(Shipment s){return new CustomerShipmentView(s.getId(),s.getDhlProductCode(),s.getMasterTrackingNumber(),s.getStatus(),s.getBillingStatus(),s.getCreatedAt(),s.getPackages().size(),s.getPackages().stream().map(p->new PackageView(p.getPackageIndex(),p.getTrackingNumber(),p.getWeight(),p.getLength(),p.getWidth(),p.getHeight())).toList(),tree(s.getSender()),tree(s.getRecipient()),s.getCustomerPrice(),s.getCurrency(),labels.findByShipmentId(s.getId()).stream().map(l->new LabelView(l.getId(),l.getFileName())).toList());}
 private JsonNode tree(String x){try{return json.readTree(x);}catch(Exception e){return json.createObjectNode();}} private Account current(){return(Account)SecurityContextHolder.getContext().getAuthentication().getPrincipal();}
 public record AddressRequest(@NotBlank String companyName,@NotBlank String contactName,@Pattern(regexp="[A-Z]{2}")String countryCode,@NotBlank String postalCode,@NotBlank String cityName,@NotBlank String addressLine1,String addressLine2,String stateOrProvinceCode,@NotBlank String phone,@Email String email){}
 public record PackageRequest(@NotNull @Positive BigDecimal weight,@NotNull @Positive BigDecimal length,@NotNull @Positive BigDecimal width,@NotNull @Positive BigDecimal height){}
 public record QuoteRequest(AddressRequest sender,@Valid @NotNull AddressRequest recipient,@NotNull LocalDateTime plannedShippingDateAndTime,boolean customsDeclarable,@Size(min=1)List<@Valid PackageRequest> packages){}
 public record ExportLineItemRequest(@Positive int number,@NotBlank @Size(min=3)String description,@NotNull @Positive BigDecimal price,@Positive int quantity,@NotBlank String quantityUnitOfMeasurement,@NotBlank @Pattern(regexp="[A-Z]{2}")String manufacturerCountry,BigDecimal netWeight,BigDecimal grossWeight,@NotBlank @Pattern(regexp="COMMERCIAL_PURPOSE_OR_SALE|PERMANENT|TEMPORARY|RETURN|USED_EXHIBITION_GOODS_TO_ORIGIN|INTERCOMPANY_USE|PERSONAL_BELONGINGS_OR_PERSONAL_USE|SAMPLE|GIFT|RETURN_TO_ORIGIN|WARRANTY_REPLACEMENT|DIPLOMATIC_GOODS|DEFENCE_MATERIAL")String exportReasonType,String commodityCode){@AssertTrue(message="at least one item weight must be positive") public boolean isWeightValid(){return(netWeight!=null&&netWeight.signum()>0)||(grossWeight!=null&&grossWeight.signum()>0);}}
 public record ExportDeclarationRequest(@NotNull @Size(min=1)List<@Valid ExportLineItemRequest> lineItems,@NotNull LocalDate invoiceDate){@AssertTrue(message="customs line item numbers must be unique")public boolean hasUniqueNumbers(){return lineItems==null||lineItems.stream().map(ExportLineItemRequest::number).distinct().count()==lineItems.size();}}
 public record CustomsDocumentRequest(@NotBlank @Pattern(regexp="CIN|INV|PNV|COO|NAF|DCL|AWB")String typeCode,@NotBlank @Pattern(regexp="PDF|JPEG|JPG|PNG")String imageFormat,@NotBlank @Size(max=6990508)String content){@AssertTrue(message="customs document must be valid Base64 and no larger than 5 MB")public boolean isValid(){try{return Base64.getDecoder().decode(content).length<=5*1024*1024;}catch(IllegalArgumentException e){return false;}}}
 public record CreateRequest(@NotBlank String productCode,@NotNull LocalDate shipDate,@NotNull LocalDateTime plannedShippingDateAndTime,boolean customsDeclarable,String description,@NotNull @PositiveOrZero BigDecimal quotedDhlCost,@Pattern(regexp="[A-Z]{3}")String currency,BigDecimal declaredValue,@Pattern(regexp="[A-Z]{3}")String declaredValueCurrency,@Pattern(regexp="CFR|CIF|CIP|CPT|DAF|DDP|DDU|DAP|DAT|DEQ|DES|EXW|FAS|FCA|FOB|DPU")String incoterm,@Valid ExportDeclarationRequest exportDeclaration,AddressRequest sender,@Valid @NotNull AddressRequest recipient,@Size(min=1)List<@Valid PackageRequest> packages,List<@Valid CustomsDocumentRequest> customsDocuments){@AssertTrue(message="declaredValueCurrency is required for customs-declarable shipments")public boolean isDeclaredValueCurrencyValid(){return !customsDeclarable||(declaredValueCurrency!=null&&!declaredValueCurrency.isBlank());}@AssertTrue(message="incoterm is required for customs-declarable shipments")public boolean isIncotermValid(){return !customsDeclarable||(incoterm!=null&&!incoterm.isBlank());}@AssertTrue(message="exportDeclaration is required for customs-declarable shipments")public boolean isExportDeclarationValid(){return !customsDeclarable||exportDeclaration!=null;}@AssertTrue(message="description must contain at least 3 characters for customs-declarable shipments")public boolean isDescriptionValid(){return !customsDeclarable||(description!=null&&description.trim().length()>=3);}}
 public record PackageView(int packageIndex,String trackingNumber,BigDecimal weight,BigDecimal length,BigDecimal width,BigDecimal height){} public record LabelView(UUID id,String fileName){} public record CustomerShipmentView(UUID id,String productCode,String masterTrackingNumber,String status,String billingStatus,Instant createdAt,int packageCount,List<PackageView> packages,JsonNode sender,JsonNode recipient,BigDecimal customerPrice,String currency,List<LabelView> labels){} public record CustomerQuote(String productCode,String productName,BigDecimal estimatedCost,String currency,String estimatedDelivery){}
}
