package hu.boltseged.shipment;
import com.fasterxml.jackson.databind.ObjectMapper; import hu.boltseged.account.Account; import hu.boltseged.billing.PricingCalculator; import hu.boltseged.label.*; import hu.boltseged.shipping.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.io.*; import java.math.*; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.security.NoSuchAlgorithmException; import java.util.*;
@Service public class ShipmentService {
 private final ShipmentRepository shipments; private final ShipmentLabelRepository labels; private final ShippingProvider dhl; private final LabelStorage storage; private final ObjectMapper json;
 public ShipmentService(ShipmentRepository s,ShipmentLabelRepository l,ShippingProvider d,LabelStorage st,ObjectMapper j){shipments=s;labels=l;dhl=d;storage=st;json=j;}
 public List<ShipmentController.CustomerQuote> quote(Account a,ShipmentController.QuoteRequest x){return dhl.quote(toQuote(x)).stream().map(q->new ShipmentController.CustomerQuote(q.productCode(),q.productName(),PricingCalculator.customerPrice(a,q.estimatedCost()),q.currency(),q.estimatedDelivery())).toList();}
 public Shipment create(Account a,String key,ShipmentController.CreateRequest x){Shipment old=shipments.findByAccountIdAndIdempotencyKey(a.getId(),key).orElse(null);if(old!=null)return old;Shipment pending=createPending(a,key,x);try{ShippingProvider.Quote selected=dhl.quote(toQuote(new ShipmentController.QuoteRequest(x.sender(),x.recipient(),x.plannedShippingDateAndTime(),x.customsDeclarable(),x.packages()))).stream().filter(q->q.productCode().equals(x.productCode())).findFirst().orElseThrow(()->new DhlApiException(org.springframework.http.HttpStatus.BAD_REQUEST,List.of("The selected DHL product is no longer available")));return complete(pending.getId(),dhl.create(toCreate(x,key)),selected.estimatedCost(),selected.currency());}catch(RuntimeException e){markFailed(pending.getId());throw e;}}
 @Transactional public Shipment createPending(Account a,String key,ShipmentController.CreateRequest x){try{Shipment shipment=new Shipment(a,key,x.productCode(),x.shipDate(),safe(x.sender()),safe(x.recipient()),x.packages().stream().map(p->new Shipment.PackageInput(p.weight(),p.length(),p.width(),p.height())).toList());shipment.setCustoms(safe(customsSnapshot(x)));return shipments.saveAndFlush(shipment);}catch(DataIntegrityViolationException e){return shipments.findByAccountIdAndIdempotencyKey(a.getId(),key).orElseThrow();}}
 @Transactional public Shipment complete(UUID id,ShippingProvider.Result r,BigDecimal cost,String currency){Shipment s=shipments.findById(id).orElseThrow();s.price(cost,PricingCalculator.customerPrice(s.getAccount(),cost));s.complete(r.masterTrackingNumber(),r.shipmentId(),r.pieceTrackingNumbers(),cost,currency);for(ShippingProvider.Label x:r.labels())try{ShipmentPackage p=x.packageIndex()==null?null:s.getPackages().get(x.packageIndex()-1);String k=storage.put(s.getId(),x.fileName(),x.contentType(),new ByteArrayInputStream(x.content()));labels.save(new ShipmentLabel(s,p,k,x.fileName(),x.contentType(),x.documentType()));}catch(IOException e){throw new IllegalStateException("DHL shipment was created but a label could not be stored",e);}return shipments.save(s);}
 @Transactional public void markFailed(UUID id){shipments.findById(id).ifPresent(s->{s.fail();shipments.save(s);});}
 private Map<String,Object> customsSnapshot(ShipmentController.CreateRequest x){Map<String,Object> snapshot=new LinkedHashMap<>();snapshot.put("customsDeclarable",x.customsDeclarable());if(x.customsDeclarable()){BigDecimal declaredValue=x.exportDeclaration().lineItems().stream().map(i->i.price().multiply(BigDecimal.valueOf(i.quantity()))).reduce(BigDecimal.ZERO,BigDecimal::add);snapshot.put("declaredValue",declaredValue);snapshot.put("declaredValueCurrency",x.declaredValueCurrency());}return snapshot;}
 private ShippingProvider.QuoteRequest toQuote(ShipmentController.QuoteRequest x){return new ShippingProvider.QuoteRequest(address(x.sender()),address(x.recipient()),x.plannedShippingDateAndTime(),x.customsDeclarable(),packages(x.packages()));}private ShippingProvider.CreateRequest toCreate(ShipmentController.CreateRequest x,String key){ShippingProvider.ExportDeclaration declaration=exportDeclaration(x.exportDeclaration(),key);BigDecimal declaredValue=x.customsDeclarable()?x.exportDeclaration().lineItems().stream().map(i->i.price().multiply(BigDecimal.valueOf(i.quantity()))).reduce(BigDecimal.ZERO,BigDecimal::add):null;List<ShippingProvider.CustomsDocument> documents=x.customsDocuments()==null?List.of():x.customsDocuments().stream().map(d->new ShippingProvider.CustomsDocument(d.typeCode(),d.imageFormat(),d.content())).toList();return new ShippingProvider.CreateRequest(x.productCode(),address(x.sender()),address(x.recipient()),x.plannedShippingDateAndTime(),x.customsDeclarable(),x.description(),declaredValue,x.declaredValueCurrency(),x.incoterm(),declaration,packages(x.packages()),documents);}private ShippingProvider.ExportDeclaration exportDeclaration(ShipmentController.ExportDeclarationRequest x,String key){if(x==null)return null;return new ShippingProvider.ExportDeclaration(x.lineItems().stream().map(i->new ShippingProvider.ExportLineItem(i.number(),i.description(),i.price(),i.quantity(),i.quantityUnitOfMeasurement(),i.manufacturerCountry(),i.netWeight(),i.grossWeight(),i.exportReasonType(),i.commodityCode())).toList(),invoiceNumber(key),x.invoiceDate());}static String invoiceNumber(String idempotencyKey){String compact=idempotencyKey.replace("-","");if(compact.matches("(?i)[0-9a-f]{32}"))return "BS-"+compact.toLowerCase(Locale.ROOT);try{return "BS-"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(idempotencyKey.getBytes(StandardCharsets.UTF_8)),0,16);}catch(NoSuchAlgorithmException e){throw new IllegalStateException("SHA-256 is unavailable",e);}}private List<ShippingProvider.Package> packages(List<ShipmentController.PackageRequest> x){return x.stream().map(p->new ShippingProvider.Package(p.weight(),p.length(),p.width(),p.height())).toList();}private ShippingProvider.Address address(ShipmentController.AddressRequest x){return new ShippingProvider.Address(x.companyName(),x.contactName(),x.countryCode(),x.postalCode(),x.cityName(),x.addressLine1(),x.addressLine2(),x.stateOrProvinceCode(),x.phone(),x.email());}private String safe(Object x){try{return json.writeValueAsString(x);}catch(Exception e){throw new IllegalArgumentException("Invalid address",e);}}
}
