package hu.boltseged.shipping;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.*; import org.springframework.boot.context.properties.*; import org.springframework.http.*; import org.springframework.stereotype.*; import org.springframework.web.client.*; import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.time.*; import java.time.format.*; import java.util.*;
/** MyDHL REST: GET /rates (one piece), POST /rates (multi-piece), POST /shipments. */
@Component public class DhlExpressShippingProvider implements ShippingProvider {
 private final DhlProperties p; private final ObjectMapper json; private final RestClient http;
 public DhlExpressShippingProvider(DhlProperties p,ObjectMapper json){this.p=p;this.json=json;http=RestClient.builder().baseUrl(p.baseUrl()).defaultHeaders(h->h.setBasicAuth(p.username,p.password,StandardCharsets.UTF_8)).build();}
 public List<Quote> quote(QuoteRequest r){configured();return parseQuotes(r.packages().size()==1?get(onePiecePath(r)):post("/rates",ratePayload(r)));}
 public Result create(CreateRequest r){configured();JsonNode root=post("/shipments",shipmentPayload(r));List<String> pieces=new ArrayList<>();for(JsonNode x:root.path("packages"))pieces.add(x.path("trackingNumber").asText(null));if(pieces.size()!=r.packages().size())throw new DhlApiException(HttpStatus.BAD_GATEWAY,List.of("DHL did not return one tracking number per package"));List<Label> labels=new ArrayList<>();for(JsonNode d:root.path("documents"))labels.add(label(d,null,labels.size()));for(int i=0;i<root.path("packages").size();i++)for(JsonNode d:root.path("packages").get(i).path("documents"))labels.add(label(d,i+1,labels.size()));return new Result(root.path("shipmentTrackingNumber").asText(null),root.path("shipmentIdentificationNumber").asText(root.path("shipmentTrackingNumber").asText(null)),pieces,labels);}
 public PickupResult createPickup(PickupRequest r){configured();JsonNode root=post("/pickups",pickupPayload(r));List<String> confirmations=new ArrayList<>(),warnings=new ArrayList<>();root.path("dispatchConfirmationNumbers").forEach(x->confirmations.add(x.asText()));root.path("warnings").forEach(x->warnings.add(x.isTextual()?x.asText():x.path("message").asText(x.toString())));if(confirmations.isEmpty())throw new DhlApiException(HttpStatus.BAD_GATEWAY,List.of("DHL did not return a pickup confirmation number"));return new PickupResult(confirmations,root.path("readyByTime").asText(null),root.path("nextPickupDate").asText(null),warnings);}
 public void cancelPickup(String confirmation,String requestorName,String reason){configured();try{http.delete().uri(b->b.path("/pickups/{confirmation}").queryParam("requestorName",requestorName).queryParam("reason",reason).build(confirmation)).retrieve().toBodilessEntity();}catch(RestClientResponseException e){throw error(e);}}
 private ObjectNode ratePayload(QuoteRequest r){ObjectNode n=common(r.plannedShippingDateAndTime());rateCustomerDetails(n,r.shipper(),r.receiver());n.put("unitOfMeasurement","metric");n.put("isCustomsDeclarable",r.customsDeclarable());ArrayNode a=n.putArray("packages");r.packages().forEach(x->a.add(pack(x)));return n;}
 ObjectNode pickupPayload(PickupRequest r){ObjectNode n=commonPickup(r.plannedPickupDateAndTime());ObjectNode details=n.putObject("customerDetails");details.set("shipperDetails",shipmentParty(r.shipper()));if(!r.pickupAddress().equals(r.shipper()))details.set("pickupDetails",shipmentParty(r.pickupAddress()));ArrayNode shipments=n.putArray("shipmentDetails");for(PickupShipment s:r.shipments()){ObjectNode x=shipments.addObject();x.put("productCode",s.productCode());x.put("isCustomsDeclarable",s.customsDeclarable());x.put("unitOfMeasurement","metric");if(s.trackingNumber()!=null&&!s.trackingNumber().isBlank())x.put("shipmentTrackingNumber",s.trackingNumber());if(s.customsDeclarable()){x.put("declaredValue",s.declaredValue());x.put("declaredValueCurrency",s.declaredValueCurrency());}ArrayNode packages=x.putArray("packages");s.packages().forEach(p->packages.add(pack(p)));}n.put("closeTime",r.closeTime().format(DateTimeFormatter.ofPattern("HH:mm")));if(r.location()!=null&&!r.location().isBlank())n.put("location",r.location());n.put("locationType",r.locationType());if(r.specialInstructions()!=null&&!r.specialInstructions().isBlank())n.putArray("specialInstructions").addObject().put("value",r.specialInstructions());return n;}
 private ObjectNode commonPickup(LocalDateTime d){ObjectNode n=json.createObjectNode();n.put("plannedPickupDateAndTime",d.atZone(ZoneId.of("Europe/Budapest")).format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss 'GMT'XXX")));n.putArray("accounts").addObject().put("typeCode","shipper").put("number",p.accountNumber);return n;}
 ObjectNode shipmentPayload(CreateRequest r){ObjectNode n=common(r.plannedShippingDateAndTime());shipmentCustomerDetails(n,r.shipper(),r.receiver());n.put("productCode",r.productCode());n.putObject("pickup").put("isRequested",false);ObjectNode c=n.putObject("content");c.put("isCustomsDeclarable",r.customsDeclarable());c.put("unitOfMeasurement","metric");c.put("description",r.description()==null||r.description().isBlank()?"Shipment":r.description());if(r.customsDeclarable()){c.put("declaredValue",r.declaredValue());c.put("declaredValueCurrency",r.declaredValueCurrency());c.put("incoterm",r.incoterm());exportDeclaration(c,r.exportDeclaration(),r.declaredValueCurrency());n.putArray("valueAddedServices").addObject().put("serviceCode","WY");}ArrayNode a=c.putArray("packages");r.packages().forEach(x->a.add(pack(x)));if(!r.customsDocuments().isEmpty()){ArrayNode docs=n.putArray("documentImages");r.customsDocuments().forEach(d->docs.addObject().put("typeCode",d.typeCode()).put("imageFormat",d.imageFormat()).put("content",d.content()));}ObjectNode o=n.putObject("outputImageProperties");o.put("printerDPI",300);o.put("encodingFormat","pdf");ArrayNode images=o.putArray("imageOptions");images.addObject().put("typeCode","waybillDoc");if(r.customsDeclarable()&&!hasCustomerInvoice(r))images.addObject().put("typeCode","invoice").put("templateName","COMMERCIAL_INVOICE_P_10").put("invoiceType","commercial").put("languageCode","eng").put("isRequested",true);return n;}
 private boolean hasCustomerInvoice(CreateRequest r){return r.customsDocuments().stream().anyMatch(d->"CIN".equals(d.typeCode())||"INV".equals(d.typeCode())||"PNV".equals(d.typeCode()));}
 private ObjectNode common(LocalDateTime d){ObjectNode n=json.createObjectNode();n.put("plannedShippingDateAndTime",d.atZone(ZoneId.of("Europe/Budapest")).format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss 'GMT'XXX")));n.putArray("accounts").addObject().put("typeCode","shipper").put("number",p.accountNumber);return n;}
 private void rateCustomerDetails(ObjectNode n,Address s,Address r){ObjectNode c=n.putObject("customerDetails");c.set("shipperDetails",rateParty(s));c.set("receiverDetails",rateParty(r));}
 private void shipmentCustomerDetails(ObjectNode n,Address s,Address r){ObjectNode c=n.putObject("customerDetails");c.set("shipperDetails",shipmentParty(s));c.set("receiverDetails",shipmentParty(r));}
 private ObjectNode rateParty(Address a){ObjectNode x=json.createObjectNode();x.put("postalCode",a.postalCode());x.put("cityName",a.cityName());x.put("countryCode",a.countryCode());return x;}
 private ObjectNode shipmentParty(Address a){ObjectNode x=json.createObjectNode();ObjectNode ad=x.putObject("postalAddress");ad.put("countryCode",a.countryCode());ad.put("postalCode",a.postalCode());ad.put("cityName",a.cityName());ad.put("addressLine1",a.addressLine1());if(a.addressLine2()!=null&&!a.addressLine2().isBlank())ad.put("addressLine2",a.addressLine2());if(a.stateOrProvinceCode()!=null&&!a.stateOrProvinceCode().isBlank())ad.put("provinceCode",a.stateOrProvinceCode());ObjectNode ci=x.putObject("contactInformation");ci.put("fullName",a.contactName());if(a.companyName()!=null&&!a.companyName().isBlank())ci.put("companyName",a.companyName());ci.put("phone",a.phone());if(a.email()!=null&&!a.email().isBlank())ci.put("email",a.email());return x;}
 private ObjectNode pack(Package x){ObjectNode n=json.createObjectNode();n.put("weight",x.weight());ObjectNode d=n.putObject("dimensions");d.put("length",x.length());d.put("width",x.width());d.put("height",x.height());return n;}
 private void exportDeclaration(ObjectNode content,ExportDeclaration declaration,String currency){ObjectNode e=content.putObject("exportDeclaration");ArrayNode items=e.putArray("lineItems");BigDecimal totalNetWeight=BigDecimal.ZERO,totalGrossWeight=BigDecimal.ZERO;for(ExportLineItem item:declaration.lineItems()){ObjectNode line=items.addObject();line.put("number",item.number());line.put("description",item.description());line.put("price",item.price());line.put("priceCurrency",currency);line.putObject("quantity").put("value",item.quantity()).put("unitOfMeasurement",item.quantityUnitOfMeasurement());if(item.commodityCode()!=null&&!item.commodityCode().isBlank())line.putArray("commodityCodes").addObject().put("typeCode","outbound").put("value",item.commodityCode());line.put("manufacturerCountry",item.manufacturerCountry());ObjectNode weight=line.putObject("weight");if(item.netWeight()!=null){weight.put("netValue",item.netWeight());totalNetWeight=totalNetWeight.add(item.netWeight());}if(item.grossWeight()!=null){weight.put("grossValue",item.grossWeight());totalGrossWeight=totalGrossWeight.add(item.grossWeight());}line.put("exportReasonType",item.exportReasonType());}e.put("totalNetWeight",totalNetWeight);e.put("totalGrossWeight",totalGrossWeight);e.putObject("invoice").put("number",declaration.invoiceNumber()).put("date",declaration.invoiceDate().toString());}
 private List<Quote> parseQuotes(JsonNode root){List<Quote> out=new ArrayList<>();for(JsonNode x:root.path("products")){JsonNode prices=x.path("totalPrice");if(!prices.isArray())continue;JsonNode q=null;for(JsonNode price:prices)if("BILLC".equalsIgnoreCase(price.path("currencyType").asText())){q=price;break;}if(q==null&&!prices.isEmpty())q=prices.get(0);if(q==null||!q.path("price").isNumber()||q.path("priceCurrency").asText().isBlank())continue;out.add(new Quote(x.path("productCode").asText(),x.path("productName").asText(),q.path("price").decimalValue(),q.path("priceCurrency").asText(),x.path("deliveryCapabilities").path("estimatedDeliveryDateAndTime").asText(null)));}return out;}
 private Label label(JsonNode x,Integer index,int n){String content=x.path("content").asText();if(content.isBlank())throw new DhlApiException(HttpStatus.BAD_GATEWAY,List.of("DHL returned a label without content"));String fmt=x.path("imageFormat").asText("PDF");return new Label(x.path("typeCode").asText("waybillDoc"),index,"label-"+(n+1)+"."+fmt.toLowerCase(),"PDF".equalsIgnoreCase(fmt)?"application/pdf":"image/"+fmt.toLowerCase(),Base64.getDecoder().decode(content));}
 private JsonNode get(String u){try{return http.get().uri(u).retrieve().body(JsonNode.class);}catch(RestClientResponseException e){throw error(e);}} private JsonNode post(String u,JsonNode b){try{return http.post().uri(u).contentType(MediaType.APPLICATION_JSON).body(b).retrieve().body(JsonNode.class);}catch(RestClientResponseException e){throw error(e);}}
private DhlApiException error(RestClientResponseException e){try{JsonNode r=json.readTree(e.getResponseBodyAsString());List<String> m=new ArrayList<>();JsonNode detail=r.path("detail");if(detail.isTextual()&&!detail.asText().isBlank())m.add(detail.asText());else if(detail.isArray())for(JsonNode x:detail){String message=x.isTextual()?x.asText():x.path("message").asText();if(!message.isBlank())m.add(message);}else if(detail.isObject()){String message=detail.path("message").asText();if(!message.isBlank())m.add(message);}JsonNode additionalDetails=r.path("additionalDetails");if(additionalDetails.isArray())for(JsonNode x:additionalDetails)if(x.isTextual()&&!x.asText().isBlank())m.add(x.asText());if(m.stream().map(String::toLowerCase).anyMatch(x->(x.contains("paperless")||x.contains("plt"))&&(x.contains("not enabled")||x.contains("not available")||x.contains("unsupported"))))m=List.of("A DHL Paperless Trade szolgáltatás nincs engedélyezve ehhez a DHL-fiókhoz.");if(m.isEmpty()&&!r.path("title").asText().isBlank())m.add(r.path("title").asText());return new DhlApiException(e.getStatusCode(),m);}catch(Exception ignored){return new DhlApiException(e.getStatusCode(),List.of("DHL could not process this shipment request"));}}
 private String onePiecePath(QuoteRequest r){Package x=r.packages().getFirst();return "/rates?accountNumber="+p.accountNumber+"&originCountryCode="+r.shipper().countryCode()+"&originPostalCode="+enc(r.shipper().postalCode())+"&originCityName="+enc(r.shipper().cityName())+"&destinationCountryCode="+r.receiver().countryCode()+"&destinationPostalCode="+enc(r.receiver().postalCode())+"&destinationCityName="+enc(r.receiver().cityName())+"&weight="+x.weight()+"&length="+x.length()+"&width="+x.width()+"&height="+x.height()+"&plannedShippingDate="+enc(r.plannedShippingDateAndTime().toLocalDate().toString())+"&isCustomsDeclarable="+r.customsDeclarable()+"&unitOfMeasurement=metric&requestEstimatedDeliveryDate=true";} private String enc(String s){return java.net.URLEncoder.encode(s,StandardCharsets.UTF_8);} private void configured(){if(p.username==null||p.username.isBlank()||p.password==null||p.password.isBlank()||p.accountNumber==null||p.accountNumber.isBlank())throw new DhlApiException(HttpStatus.SERVICE_UNAVAILABLE,List.of("DHL shipping is not configured"));}
 @ConfigurationProperties(prefix="dhl") public static class DhlProperties {String apiBaseUrl,username,password,accountNumber;boolean testMode;public String baseUrl(){return apiBaseUrl==null||apiBaseUrl.isBlank()?(testMode?"https://express.api.dhl.com/mydhlapi/test":"https://express.api.dhl.com/mydhlapi"):apiBaseUrl;}public void setApiBaseUrl(String v){apiBaseUrl=v;}public void setUsername(String v){username=v;}public void setPassword(String v){password=v;}public void setAccountNumber(String v){accountNumber=v;}public void setTestMode(boolean v){testMode=v;}}
}
