package hu.boltseged.shipment;
import com.fasterxml.jackson.databind.ObjectMapper; import hu.boltseged.account.Account; import hu.boltseged.label.*; import hu.boltseged.shipping.ShippingProvider; import org.junit.jupiter.api.Test; import java.math.*; import java.time.*; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
class ShipmentServicePricingTest {
 private final ShipmentRepository shipments=mock(ShipmentRepository.class); private final ShipmentLabelRepository labels=mock(ShipmentLabelRepository.class); private final ShippingProvider carrier=mock(ShippingProvider.class); private final ShipmentService service=new ShipmentService(shipments,labels,carrier,mock(LabelStorage.class),new ObjectMapper());
 private Account account(String type,BigDecimal value){Account a=new Account("Saved sender","a@example.com","hash","CUSTOMER");a.update("Saved sender",null,null,"Saved contact","a@example.com",type,value);a.updateCompanyProfile("Saved sender",null,null,"Saved contact","HU","1051","Budapest","Saved Street",null,null,"+361",null,null,null,null,null,null,null,null,null,null);return a;} private ShipmentController.QuoteRequest request(){ShipmentController.AddressRequest address=new ShipmentController.AddressRequest("Untrusted","Untrusted","HU","9999","Elsewhere","Client Street",null,null,"+999","client@example.com");return new ShipmentController.QuoteRequest(address,address,LocalDateTime.of(2026,1,2,10,0),false,List.of(new ShipmentController.PackageRequest(BigDecimal.ONE,BigDecimal.ONE,BigDecimal.ONE,BigDecimal.ONE)));}
 @Test void fixedCustomerQuoteMarksUpRawCarrierPriceWithoutExposingIt(){when(carrier.quote(any())).thenReturn(List.of(new ShippingProvider.Quote("P","Express",new BigDecimal("8470"),"HUF",null)));ShipmentController.CustomerQuote quote=service.quote(account("FIXED",new BigDecimal("1000")),request()).getFirst();assertEquals(new BigDecimal("9470.00"),quote.estimatedCost());assertEquals("HUF",quote.currency());assertFalse(Arrays.stream(ShipmentController.CustomerQuote.class.getRecordComponents()).anyMatch(c->c.getName().equals("dhlEstimatedCost")||c.getName().equals("rawCost")));}
 @Test void percentageCustomerQuoteUsesPricingCalculator(){when(carrier.quote(any())).thenReturn(List.of(new ShippingProvider.Quote("P","Express",new BigDecimal("8470"),"HUF",null)));assertEquals(new BigDecimal("9317.00"),service.quote(account("PERCENTAGE",new BigDecimal("10")),request()).getFirst().estimatedCost());}
 @Test void quoteUsesAuthenticatedAccountSenderInsteadOfRequestSender(){when(carrier.quote(any())).thenReturn(List.of(new ShippingProvider.Quote("P","Express",BigDecimal.ONE,"HUF",null)));service.quote(account("FIXED",BigDecimal.ZERO),request());org.mockito.ArgumentCaptor<ShippingProvider.QuoteRequest> captured=org.mockito.ArgumentCaptor.forClass(ShippingProvider.QuoteRequest.class);verify(carrier).quote(captured.capture());assertEquals("Saved sender",captured.getValue().shipper().companyName());assertEquals("Saved Street",captured.getValue().shipper().addressLine1());}
 @Test void incompleteSenderProfileBlocksQuote(){Account incomplete=new Account(null,"a@example.com","hash","CUSTOMER");org.springframework.web.server.ResponseStatusException error=assertThrows(org.springframework.web.server.ResponseStatusException.class,()->service.quote(incomplete,request()));assertTrue(error.getReason().contains("Feladói adatok"));verifyNoInteractions(carrier);}
 @Test void completionSnapshotsRawCostAndSingleMarkup(){Account a=account("FIXED",new BigDecimal("1000"));Shipment shipment=new Shipment(a,"key","P",LocalDate.now(),"{}","{}",List.of(new Shipment.PackageInput(BigDecimal.ONE,BigDecimal.ONE,BigDecimal.ONE,BigDecimal.ONE)));when(shipments.findById(shipment.getId())).thenReturn(Optional.of(shipment));when(shipments.save(any())).thenAnswer(i->i.getArgument(0));service.complete(shipment.getId(),new ShippingProvider.Result("tracking","shipment",List.of("piece"),List.of()),new BigDecimal("8470"),"HUF");assertEquals(new BigDecimal("8470"),shipment.getDhlEstimatedCost());assertEquals(new BigDecimal("9470.00"),shipment.getCustomerPrice());}
}
