package hu.boltseged.shipment;
import com.fasterxml.jackson.databind.ObjectMapper; import hu.boltseged.account.Account; import hu.boltseged.label.*; import hu.boltseged.shipping.ShippingProvider; import org.junit.jupiter.api.Test; import java.math.*; import java.time.*; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
class ShipmentServicePricingTest {
 private final ShipmentRepository shipments=mock(ShipmentRepository.class); private final ShipmentLabelRepository labels=mock(ShipmentLabelRepository.class); private final ShippingProvider carrier=mock(ShippingProvider.class); private final ShipmentService service=new ShipmentService(shipments,labels,carrier,mock(LabelStorage.class),new ObjectMapper());
 private Account account(String type,BigDecimal value){Account a=new Account("A","a@example.com","hash","CUSTOMER");a.update("A",null,null,"A","a@example.com",type,value);return a;} private ShipmentController.QuoteRequest request(){ShipmentController.AddressRequest address=new ShipmentController.AddressRequest("A","A","HU","1051","Budapest","Street",null,null,"+361","a@example.com");return new ShipmentController.QuoteRequest(address,address,LocalDateTime.of(2026,1,2,10,0),false,List.of(new ShipmentController.PackageRequest(BigDecimal.ONE,BigDecimal.ONE,BigDecimal.ONE,BigDecimal.ONE)));}
 @Test void fixedCustomerQuoteMarksUpRawCarrierPriceWithoutExposingIt(){when(carrier.quote(any())).thenReturn(List.of(new ShippingProvider.Quote("P","Express",new BigDecimal("8470"),"HUF",null)));ShipmentController.CustomerQuote quote=service.quote(account("FIXED",new BigDecimal("1000")),request()).getFirst();assertEquals(new BigDecimal("9470.00"),quote.estimatedCost());assertEquals("HUF",quote.currency());assertFalse(Arrays.stream(ShipmentController.CustomerQuote.class.getRecordComponents()).anyMatch(c->c.getName().equals("dhlEstimatedCost")||c.getName().equals("rawCost")));}
 @Test void percentageCustomerQuoteUsesPricingCalculator(){when(carrier.quote(any())).thenReturn(List.of(new ShippingProvider.Quote("P","Express",new BigDecimal("8470"),"HUF",null)));assertEquals(new BigDecimal("9317.00"),service.quote(account("PERCENTAGE",new BigDecimal("10")),request()).getFirst().estimatedCost());}
 @Test void completionSnapshotsRawCostAndSingleMarkup(){Account a=account("FIXED",new BigDecimal("1000"));Shipment shipment=new Shipment(a,"key","P",LocalDate.now(),"{}","{}",List.of(new Shipment.PackageInput(BigDecimal.ONE,BigDecimal.ONE,BigDecimal.ONE,BigDecimal.ONE)));when(shipments.findById(shipment.getId())).thenReturn(Optional.of(shipment));when(shipments.save(any())).thenAnswer(i->i.getArgument(0));service.complete(shipment.getId(),new ShippingProvider.Result("tracking","shipment",List.of("piece"),List.of()),new BigDecimal("8470"),"HUF");assertEquals(new BigDecimal("8470"),shipment.getDhlEstimatedCost());assertEquals(new BigDecimal("9470.00"),shipment.getCustomerPrice());}
}
