package hu.boltseged.config;
import hu.boltseged.account.*; import io.jsonwebtoken.*; import io.jsonwebtoken.security.Keys; import jakarta.servlet.*; import jakarta.servlet.http.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.context.annotation.*; import org.springframework.security.authentication.*; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.core.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.*; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import org.springframework.web.filter.OncePerRequestFilter; import javax.crypto.SecretKey; import java.io.IOException; import java.nio.charset.StandardCharsets; import java.util.*;
@Configuration @org.springframework.boot.context.properties.EnableConfigurationProperties(hu.boltseged.shipping.DhlExpressShippingProvider.DhlProperties.class)
public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean SecurityFilterChain filter(HttpSecurity h,JwtFilter f)throws Exception{return h.csrf(c->c.disable()).cors(c->{}).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/auth/**","/actuator/health").permitAll().requestMatchers("/api/admin/**").hasRole("ADMIN").anyRequest().authenticated()).addFilterBefore(f,UsernamePasswordAuthenticationFilter.class).build();}
 @Bean JwtFilter jwtFilter(AccountRepository r,@Value("${app.jwt-secret}")String secret){return new JwtFilter(r,secret);}
 public static class JwtFilter extends OncePerRequestFilter {final AccountRepository repo;final SecretKey key; JwtFilter(AccountRepository r,String s){repo=r;key=Keys.hmacShaKeyFor(s.getBytes(StandardCharsets.UTF_8));} protected void doFilterInternal(HttpServletRequest q,HttpServletResponse p,FilterChain c)throws IOException,ServletException{String x=q.getHeader("Authorization");if(x!=null&&x.startsWith("Bearer "))try{String e=Jwts.parser().verifyWith(key).build().parseSignedClaims(x.substring(7)).getPayload().getSubject();repo.findByEmailIgnoreCase(e).filter(Account::isActive).ifPresent(a->SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(a,null,List.of(new SimpleGrantedAuthority("ROLE_"+a.getRole())))));}catch(JwtException ignored){}c.doFilter(q,p);}}
}
