<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api, ApiError } from '../api'
const profile = ref<any>({}), currentPassword = ref(''), newPassword = ref(''), confirmation = ref('')
const message = ref(''), error = ref(''), loading = ref(true), saving = ref(false)
onMounted(async () => { try { profile.value = await api('/api/account/profile') } catch (e) { error.value = e instanceof ApiError ? e.message : 'Az adatok betöltése nem sikerült.' } finally { loading.value = false } })
async function save() { message.value = ''; error.value = ''; if (newPassword.value !== confirmation.value) { error.value = 'Az új jelszavak nem egyeznek.'; return }; saving.value = true; try { await api('/api/account/password', { method: 'POST', body: JSON.stringify({ currentPassword: currentPassword.value, newPassword: newPassword.value }) }); currentPassword.value = ''; newPassword.value = ''; confirmation.value = ''; message.value = 'Jelszó sikeresen módosítva.' } catch (e) { error.value = e instanceof ApiError ? e.message : 'A jelszó módosítása nem sikerült.' } finally { saving.value = false } }
</script>
<template><section class="card narrow"><p class="eyebrow">Fiókbeállítások</p><h1>Fiók</h1><p v-if="loading" class="muted">Betöltés…</p><template v-else><label>E-mail<input :value="profile.email" readonly></label><h2>Jelszó módosítása</h2><form @submit.prevent="save"><label>Jelenlegi jelszó<input v-model="currentPassword" required type="password" autocomplete="current-password"></label><label>Új jelszó<input v-model="newPassword" required minlength="12" type="password" autocomplete="new-password"></label><label>Új jelszó megerősítése<input v-model="confirmation" required minlength="12" type="password" autocomplete="new-password"></label><p v-if="error" class="alert error">{{ error }}</p><p v-if="message" class="alert success-text">{{ message }}</p><button :disabled="saving">{{ saving ? 'Mentés…' : 'Jelszó módosítása' }}</button></form></template></section></template>
