<script setup lang="ts">
import { onMounted, ref } from 'vue'
const rows=ref<any[]>([]),accounts=ref<any[]>([]),summary=ref<any[]>([]),selected=ref<string[]>([])
const accountId=ref(''),from=ref(''),to=ref(''),billingStatus=ref('UNBILLED'),loading=ref(false),error=ref('')
const h=()=>({Authorization:`Bearer ${localStorage.getItem('token')}`})
function query(){const p=new URLSearchParams({size:'25',sort:'createdAt,desc'});if(accountId.value)p.set('accountId',accountId.value);if(from.value)p.set('from',from.value);if(to.value)p.set('to',to.value);if(billingStatus.value)p.set('billingStatus',billingStatus.value);return p}
async function load(){loading.value=true;error.value='';try{const p=query(),sp=new URLSearchParams(p);sp.delete('size');sp.delete('sort');const [list,total]=await Promise.all([fetch(`/api/admin/billing?${p}`,{headers:h()}),fetch(`/api/admin/billing/summary?${sp}`,{headers:h()})]);if(!list.ok||!total.ok)throw new Error('A számlázási adatok nem tölthetők be.');rows.value=(await list.json()).content||[];summary.value=await total.json()}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function loadAccounts(){const r=await fetch('/api/admin/accounts',{headers:h()});if(r.ok)accounts.value=await r.json()}
async function exportCsv(){const r=await fetch(`/api/admin/billing/csv?${query().toString()}`,{headers:h()});if(!r.ok){error.value='A CSV export nem tölthető le.';return}const a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download='billing.csv';a.click();URL.revokeObjectURL(a.href)}
async function invoice(){if(!selected.value.length||!confirm('A kijelölt küldemények számlázottra állítása?'))return;await fetch('/api/admin/billing/invoice',{method:'POST',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify(selected.value)});selected.value=[];await load()}
onMounted(()=>{loadAccounts();load()})
</script>
<template><section class="card"><div class="card-head"><h1>Számlázás</h1><button class="button" @click="exportCsv">CSV export</button></div><div class="filters"><label>Ügyfél <select v-model="accountId" @change="load"><option value="">Mindegyik</option><option v-for="a in accounts" :key="a.id" :value="a.id">{{a.companyName}}</option></select></label><label>Tól <input v-model="from" type="date" @change="load"></label><label>Ig <input v-model="to" type="date" @change="load"></label><label>Számlázási állapot <select v-model="billingStatus" @change="load"><option value="UNBILLED">UNBILLED</option><option value="INVOICED">INVOICED</option></select></label></div><p v-if="error" class="error">{{error}}</p><div v-for="total in summary" :key="total.currency" class="stats compact"><span>Darab: <b>{{total.shipmentCount||0}}</b></span><span>DHL: <b>{{total.totalDhlEstimatedCost||0}} {{total.currency}}</b></span><span>Ügyfélár: <b>{{total.totalCustomerPrice||0}} {{total.currency}}</b></span><span>Árrés: <b>{{total.totalMargin||0}} {{total.currency}}</b></span></div><button @click="invoice" :disabled="!selected.length||loading">Kijelöltek számlázottra állítása</button><span v-if="loading"> Betöltés…</span><table><thead><tr><th></th><th>Cég</th><th>Tracking</th><th>Csomag</th><th>DHL költség</th><th>Ügyfélár</th><th>Pénznem</th><th>Állapot</th></tr></thead><tbody><tr v-for="x in rows" :key="x.id"><td><input v-if="x.billingStatus==='UNBILLED'" v-model="selected" type="checkbox" :value="x.id"></td><td>{{x.company}}</td><td>{{x.masterTrackingNumber||'—'}}</td><td>{{x.packageCount}}</td><td>{{x.dhlEstimatedCost}}</td><td>{{x.customerPrice}}</td><td>{{x.currency}}</td><td>{{x.billingStatus}}</td></tr></tbody></table></section></template>
