<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api, apiBlob, ApiError } from '../api'
import { billingStatusLabel, dateTime, money, productLabel, statusLabel } from '../customer'
const route=useRoute(), item=ref<any>(), loading=ref(true), error=ref(''), notFound=ref(false), downloading=ref<string>(''), copied=ref('')
const fields=[['companyName','Cégnév'],['contactName','Kapcsolattartó'],['addressLine1','Cím'],['addressLine2','Cím kiegészítés'],['postalCode','Irányítószám'],['cityName','Város'],['stateOrProvinceCode','Állam / megye'],['countryCode','Ország'],['phone','Telefon'],['email','E-mail']]
async function load(){loading.value=true;error.value='';notFound.value=false;try{item.value=await api(`/api/shipments/${route.params.id}`)}catch(e){if(e instanceof ApiError&&e.status===404)notFound.value=true;else error.value=e instanceof ApiError?e.message:'A küldemény betöltése nem sikerült.'}finally{loading.value=false}}
async function copy(value?:string){if(!value)return;try{await navigator.clipboard?.writeText(value);copied.value=value;setTimeout(()=>copied.value='',1600)}catch{error.value='A másolás nem sikerült.'}}
async function download(id:string,name:string){downloading.value=id;error.value='';try{const blob=await apiBlob(`/api/shipments/${item.value.id}/labels/${id}`);const href=URL.createObjectURL(blob), link=document.createElement('a');link.href=href;link.download=name;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(href)}catch(e){error.value=e instanceof ApiError?e.message:'A dokumentum letöltése nem sikerült.'}finally{downloading.value=''}}
onMounted(load)
</script>
<template><p v-if="loading" class="empty">Betöltés…</p><section v-else-if="notFound" class="card empty">A küldemény nem található.<br><RouterLink class="button" to="/shipments">Vissza a küldeményekhez</RouterLink></section><section v-else-if="item"><RouterLink class="text-link" to="/shipments">← Vissza a küldeményekhez</RouterLink><div class="hero detail-head"><div><p class="eyebrow">Küldemény</p><h1>Küldemény részletei</h1><p class="muted">{{ dateTime(item.createdAt) }} · {{ productLabel(item.productCode) }}</p></div><span class="pill" :class="`status-${item.status.toLowerCase()}`">{{ statusLabel(item.status) }}</span></div><p v-if="error" class="alert error">{{ error }}</p><section class="card summary"><div><small>Master tracking</small><strong v-if="item.masterTrackingNumber" class="tracking">{{ item.masterTrackingNumber }}</strong><span v-else class="muted">Még nem érhető el</span><button v-if="item.masterTrackingNumber" class="copy" @click="copy(item.masterTrackingNumber)">{{ copied===item.masterTrackingNumber?'Másolva':'Másolás' }}</button></div><div><small>Ügyfélár</small><strong>{{ item.customerPrice == null?'Ár előkészítés alatt':money(item.customerPrice,item.currency) }}</strong></div><div v-if="item.billingStatus"><small>Számlázás</small><span>{{ billingStatusLabel(item.billingStatus) }}</span></div></section><div class="detail-grid"><section class="card"><h2>Feladó</h2><dl><template v-for="[key,label] in fields" :key="key"><dt v-if="item.sender?.[key]">{{ label }}</dt><dd v-if="item.sender?.[key]">{{ item.sender[key] }}</dd></template></dl></section><section class="card"><h2>Címzett</h2><dl><template v-for="[key,label] in fields" :key="key"><dt v-if="item.recipient?.[key]">{{ label }}</dt><dd v-if="item.recipient?.[key]">{{ item.recipient[key] }}</dd></template></dl></section></div><section class="card"><h2>Csomagok ({{ item.packageCount }})</h2><div v-for="p in item.packages" :key="p.packageIndex" class="package-card"><h3>Csomag {{ p.packageIndex }}</h3><p v-if="p.trackingNumber"><strong>Tracking: {{ p.trackingNumber }}</strong> <button class="copy" @click="copy(p.trackingNumber)">{{ copied===p.trackingNumber?'Másolva':'Másolás' }}</button></p><p v-else class="muted">Tracking előkészítés alatt</p><p>{{ p.weight }} kg · {{ p.length }} × {{ p.width }} × {{ p.height }} cm</p></div></section><section class="card"><h2>Dokumentumok</h2><p v-if="!item.labels?.length" class="muted">Még nincs elérhető dokumentum.</p><div v-for="label in item.labels" :key="label.id" class="document"><span>{{ label.fileName }}</span><button :disabled="downloading===label.id" @click="download(label.id,label.fileName)">{{ downloading===label.id?'Letöltés…':'Letöltés' }}</button></div></section></section><section v-else class="card empty"><p class="alert error">{{ error||'A küldemény betöltése nem sikerült.' }}</p><button @click="load">Újrapróbálás</button></section></template>
