<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, ApiError } from '../api'
import { dateTime, money, productLabel, statusLabel } from '../customer'

type Shipment = { id:string; createdAt:string; productCode?:string; masterTrackingNumber?:string; packageCount:number; packages:{trackingNumber?:string}[]; recipient?:Record<string,string>; customerPrice?:number; currency:string; status:string }
const shipments=ref<Shipment[]>([]), loading=ref(true), error=ref(''), search=ref(''), status=ref(''), newest=ref(true)
const recipient=(s:Shipment)=>s.recipient?.companyName||s.recipient?.contactName||'—'
const destination=(s:Shipment)=>s.recipient?.countryCode||'—'
const filtered=computed(()=>shipments.value.filter(s=>{const needle=search.value.trim().toLocaleLowerCase('hu-HU');const haystack=[s.masterTrackingNumber,s.recipient?.companyName,s.recipient?.contactName,s.recipient?.cityName,s.recipient?.postalCode,s.recipient?.countryCode,...s.packages.map(p=>p.trackingNumber)].filter(Boolean).join(' ').toLocaleLowerCase('hu-HU');return(!status.value||s.status===status.value)&&(!needle||haystack.includes(needle))}).sort((a,b)=>(new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())*(newest.value?1:-1)))
async function load(){loading.value=true;error.value='';try{shipments.value=await api('/api/shipments')}catch(e){error.value=e instanceof ApiError?e.message:'A küldemények betöltése nem sikerült.'}finally{loading.value=false}}
onMounted(load)
</script>
<template><div class="hero"><div><p class="eyebrow">Szállítmányok</p><h1>Küldeményeim</h1><p class="muted">Keresd meg és kövesd korábbi küldeményeidet.</p></div><RouterLink class="button" to="/shipments/new">+ Új küldemény</RouterLink></div><p v-if="error" class="alert error">{{ error }} <button class="link-button" @click="load">Újrapróbálás</button></p><section class="card"><div class="filters"><label>Keresés<input v-model="search" placeholder="Tracking, címzett vagy célország"></label><label>Állapot<select v-model="status"><option value="">Összes</option><option value="CREATED">Létrehozva</option><option value="PENDING">Feldolgozás alatt</option><option value="FAILED">Sikertelen</option></select></label><label>Rendezés<select v-model="newest"><option :value="true">Legújabb elöl</option><option :value="false">Legrégebbi elöl</option></select></label></div><div v-if="loading" class="empty">Betöltés…</div><div v-else-if="!shipments.length" class="empty">Még nincs küldeményed.<br><RouterLink class="button" to="/shipments/new">Első küldemény létrehozása</RouterLink></div><div v-else-if="!filtered.length" class="empty">Nincs a keresésnek megfelelő küldemény.</div><template v-else><div class="desktop-table"><table><thead><tr><th>Dátum</th><th>Címzett</th><th>Célország</th><th>DHL szolgáltatás</th><th>Tracking</th><th>Csomagok</th><th>Ár</th><th>Állapot</th><th></th></tr></thead><tbody><tr v-for="s in filtered" :key="s.id"><td>{{ dateTime(s.createdAt) }}</td><td>{{ recipient(s) }}</td><td>{{ destination(s) }}</td><td>{{ productLabel(s.productCode) }}</td><td>{{ s.masterTrackingNumber||'—' }}</td><td>{{ s.packageCount }}</td><td>{{ s.customerPrice == null ? '—' : money(s.customerPrice,s.currency) }}</td><td><span class="pill" :class="`status-${s.status.toLowerCase()}`">{{ statusLabel(s.status) }}</span></td><td><RouterLink class="text-link" :to="`/shipments/${s.id}`">Részletek</RouterLink></td></tr></tbody></table></div><div class="shipment-cards"><article v-for="s in filtered" :key="s.id" class="shipment-card"><div><span class="pill" :class="`status-${s.status.toLowerCase()}`">{{ statusLabel(s.status) }}</span><h3>{{ recipient(s) }}</h3><p>{{ dateTime(s.createdAt) }} · {{ destination(s) }}</p><p>{{ s.masterTrackingNumber||'Tracking előkészítés alatt' }}</p><strong>{{ s.customerPrice == null ? 'Ár előkészítés alatt' : money(s.customerPrice,s.currency) }}</strong></div><RouterLink class="button secondary" :to="`/shipments/${s.id}`">Részletek</RouterLink></article></div></template></section></template>
